### ISSUE TITLE
Spaces/newline inside html causes ppx failure

### ISSUE THREAD

**Issue by Drup** [ocsigen/tyxml#119]
@aantron As discussed. Do you have an angle on this one ? I have really no idea how to solve itL Should it be solved in tyxml or markup ?

This is the last thing that is really blocking for the release, Locations can benefit from later improvements.

**Comment by aantron** [comment]
The PPX actually used to filter whitespace in `html` elements correctly in the original PR, but this was broken during later changes. I will fix it and add a test – the latter in part to get me used to the testing setup.

**Comment by aantron** [comment]
Oh, and to answer the other query, it should be solved in TyXML. Markup.ml is correct (with respect to the HTML5 spec) in emitting this particular whitespace. It would be odd to add a special filtering helper to Markup.ml for this use case.

**Comment by Drup** [comment]
This is actually not solved just yet: 

```ocaml
# [%html 
  {|<html>
     <head>
       <title>mytitle</title>
     </head>
     <body>mycontent</body>
   </html>
  |}]
;;
- : [> `Html | `PCDATA ] Tyxml_html.elt list
```

It should be one Html element, not a list. Should we remove whitespace at the beginning and the end of the quotations ?

**Comment by Drup** [comment]
Solved by https://github.com/ocsigen/tyxml/pull/121
